databases:
  - name: bulletinboard
    plan: free
    databaseName: bulletinboard
    user: bulletinboard

services:
  - type: web
    name: bulletinboard
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bulletinboard
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
